### PR TITLE
[WIP] Add Capistrano recipes

### PR DESCRIPTION
**Pull request by sponomarev**
Waiting for https://github.com/palkan/anyway_config/pull/27

### CODE REVIEW

**Comment by palkan** [comment]
What do you think about adding it as a separate gem?

**Comment by sponomarev** [comment]
I don’t see a reason. Just a couple of bytes to the final size. Any other considerations?

**Comment by sponomarev** [comment]
Ah, maybe anycable-rails is more suitable?

**Comment by palkan** [comment]
> Ah, maybe anycable-rails is more suitable?

That's the first reason)

But the main reason is that I don't want to release the gem just to fix/update Capistrano task, 'cause the latter one is not used by everyone or even most users. They shouldn't be bothered by outdated version in case this version doesn't affect the library itself.

**Comment by sponomarev** [comment]
Honestly, I don't care. I've written a piece of code which your users could find useful and make the adaptation process a piece of cake. I can make it production-proof, I can reflect any reasonable proposals, I can document it. What I don't want to do is to create a new gem and be responsible for it. 🤷‍♂️ You're the author, and the final decision is on you. I don't mind making a PR to whatever Github project you want.

**Comment by palkan** [comment]
> What I don't want to do is to create a new gem and be responsible for it

So, you want me to be responsible for the code I have no idea about?)

> I don't mind making a PR to whatever Github project you want.

Ok. Then let's use this one: https://github.com/anycable/capistrano-anycable

**Comment by sponomarev** [comment]
> So, you want me to be responsible for the code I have no idea about?)

Nope. Just maintaining a gem, creating, publishing, receiving PRs or whatever in case I die or decided to downshift somewhere in  Nepal. 

> Ok. Then let's use this one: https://github.com/anycable/capistrano-anycable

Thanks! ❤️

**Pull request closed without merging**
