### PR TITLE
Add Anycable::Server#stop method

### PR DESCRIPTION
**Pull request by sadovnik**

### CODE REVIEW

**Comment by palkan** [comment]
Please, rebase.

And do not update version.

**Comment by sadovnik** [comment]
Done.

Btw, you forgot to add git tag for `0.4.5` version.

**Comment by palkan** [comment]
@sadovnik please, rebase; there should be the only one commit (without merge commits)

**Comment by palkan** [comment]
Merged through https://github.com/anycable/anycable/commit/dcc48f9e7b9e1e66648ec2e9eb8062e1d0faa5e9

**Pull request closed without merging**
